ci - move postgres db_data to avoid clash with uv
Install uv
…
Searching files using cache dependency glob: **/uv.lock,**/requirements*.txt
Error: EACCES: permission denied, scandir '/home/runner/work/acmetk/acmetk/db_data'